LogAlyzer/force-app/main/default/objects/Log_File__c/Log_File__c.object-meta.xml
<CustomObject>
    <description>Object representing a single log file</description>
    <label>Log File</label>
    <nameField>
        <displayFormat>L{0000}</displayFormat>
        <label>LogNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LogAlyzer/force-app/main/default/objects/Log_File__c/fields/LogId__c.field-meta.xml
<CustomField>
    <fullName>LogId__c</fullName>
    <label>LogId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

LogAlyzer/force-app/main/default/objects/Log_Line__c/Log_Line__c.object-meta.xml
<CustomObject>
    <label>Log Line</label>
    <nameField>
        <displayFormat>LL{00000000}</displayFormat>
        <label>LineNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LogAlyzer/force-app/main/default/objects/Log_Line__c/fields/Log_Data__c.field-meta.xml
<CustomField>
    <fullName>Log_Data__c</fullName>
    <label>Log Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LogAlyzer/force-app/main/default/objects/Log_Line__c/fields/Log_File__c.field-meta.xml
<CustomField>
    <fullName>Log_File__c</fullName>
    <label>Log File</label>
    <referenceTo>Log_File__c</referenceTo>
    <relationshipLabel>Log Lines</relationshipLabel>
    <relationshipName>Log_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LogAlyzer/force-app/main/default/classes/LogUtil.cls
public class LogUtil {

  Public Static Void digestLog(Id LogFileId) {
      Log_File__c LogFile = [select ID, LogId__c from Log_File__c where Id = :LogFileId];
      
      if (LogFile!=null) {
          digestLog(LogFile);
      }
        
  }
  
  Public Static Void digestLog(Log_File__c LogFile) {
      //Delete Existing Log Lines
     // List<id> linesToDel = new List<id>();
     // For (Log_Line__c ll : [select id from Log_Line__c where Log_file__c = :LogFile.id]) {
      //    linesToDel.add(ll.id);
      //}
      //deleteLogLines(linesToDel);
      
            
      Id ApexLogId = LogFile.LogId__c;
      String LogBody = getBody(ApexLogId);
      List<Log_Line__c> LogLines = new List<Log_Line__c>();
      for(String line : LogBody.split('\n')) {
          Log_Line__c l = new Log_Line__c(Log_File__c = LogFile.id,  Log_Data__c = line );
          LogLines.add(l);
      }
      insert(LogLines);
  }
  
  
  Public static void deleteLines(List<Log_Line__c> DelLines) {
      If (DelLines.size() > 0) {
          delete DelLines;
          Database.emptyRecycleBin(DelLines);
      }  
  }
  
  Public static String getBody(Id ApexLogId) {
    // Instantiate a new http object
    String hostURL= 'https://na50.salesforce.com';
    String requestPath = '/services/data/v40.0/sobjects/ApexLog/' + ApexLogId + '/Body';
    
    Http h = new Http();

    // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
    HttpRequest req = new HttpRequest();
    req.setEndpoint(hostUrl + requestPath);
    req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionID());
    req.setHeader('Content-Type', 'application/json');
    req.setMethod('GET');

    // Send the request, and return a response
    HttpResponse res = h.send(req);
    return res.getBody();
  }
    
}